import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer";
import RecoilRootWrapper from "./recoilRootWrapper";
import { Toaster } from "react-hot-toast";

const poppin = Poppins({ 
  weight: '400',
  subsets: ['latin'] ,
})

export const metadata: Metadata = {
  title: "Tech ShopV2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppin.className}>
        <RecoilRootWrapper>
          <Toaster position="top-center" />
          <Navbar/>
            {children}
          <Footer/>
        </RecoilRootWrapper>
        </body>
    </html>
  );
}
